spring:
  cloud:
    function:
      definition: orderCreated;invoiceCreated
    stream:
      bindings:
        orderCreated-in-0:
          destination: orders
        invoiceCreated-in-0:
          destination: invoices
logging:
  level:
    root: info
    org:
      springframework: info

